# Site settings
language: ""
name: LampApps
description: "Site description"
google-verification: ""
markdown: kramdown
highlighter: rouge

# Handling Reading
include:
  #- ".htaccess"
  #- "_pages"

exclude:
  #- "/assets/"
  #- "bower.json"
  #- "composer.json"
  #- "composer.lock"
  #- "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  #- "/gulp/"
  #- "gulpfile.js"
  #- "LICENSE.md"
  #- "Makefile"
  #- "node_modules"
  #- "npm-debug.log"
  #- "package.json"
  - "README.md"
  #- "rev-manifest.json"
  - "s3_website.yml"

# Plugins
gems: ["jekyll-sitemap", "jekyll-paginate", "sass"]

# Conversion
#incremental:      true

# Serving
url: "http://www.lampapps.com.s3-website-us-east-1.amazonaws.com"
# baseurl:  "" # does not include hostname

sass:
  style: compressed

# Outputting
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title.html
paginate: 5
paginate_path: "blog/page:num"
