name: LampApps
# Comment next line for local server
url: "devlampapps.s3-website-us-east-1.amazonaws.com"
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title.html
paginate: 3
paginate_path: "blog/page:num"
#Gems
gems: [jekyll-paginate]